/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC721Transfer__factory } from "./IERC721Transfer__factory";
export { ISPIC__factory } from "./ISPIC__factory";
