/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20MockSol from "./ERC20Mock.sol";
export type { erc20MockSol };
import type * as erc721MockSol from "./ERC721Mock.sol";
export type { erc721MockSol };
