/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as verifierIcSol from "./verifierIc.sol";
export type { verifierIcSol };
import type * as verifierVcSol from "./verifierVc.sol";
export type { verifierVcSol };
