/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { ERC721 } from "./ERC721";
export type { SPIC } from "./SPIC";

export { ERC20__factory } from "./factories/ERC20__factory";
export { ERC721__factory } from "./factories/ERC721__factory";
export { SPIC__factory } from "./factories/SPIC__factory";
